# Generated by Django 5.0.7 on 2025-04-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_management.component'),
        ),
    ]
